[project]
name = "spotibot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "python-telegram-bot~=22.2",
    "spotipy>=2.22.1,<3",
]